import { Game, GameStatus } from "./types";

// This is the initial data. In a real scenario, the user would replace this 
// with the JSON generated by the Admin panel.
export const INITIAL_GAMES: Game[] = [
  {
    id: '1',
    title: 'Elden Ring',
    status: GameStatus.COMPLETED,
    genre: ['RPG', 'Open World'],
    rating: 10,
    description: "Un chef-d'œuvre absolu. L'exploration est incroyable.",
    releaseYear: 2022,
    coverUrl: 'https://picsum.photos/300/400?random=1'
  },
  {
    id: '2',
    title: 'Hollow Knight',
    status: GameStatus.COMPLETED,
    genre: ['Metroidvania', 'Platformer'],
    rating: 9.5,
    description: "Dur mais juste. L'ambiance est magnifique.",
    releaseYear: 2017,
    coverUrl: 'https://picsum.photos/300/400?random=2'
  },
  {
    id: '3',
    title: 'Silksong',
    status: GameStatus.PLANNED,
    genre: ['Metroidvania'],
    description: "On attend toujours...",
    coverUrl: 'https://picsum.photos/300/400?random=3'
  },
   {
    id: '4',
    title: 'Getting Over It',
    status: GameStatus.DROPPED,
    genre: ['Psychological Horror'],
    description: "Ma santé mentale est plus importante.",
    releaseYear: 2017,
    coverUrl: 'https://picsum.photos/300/400?random=4'
  }
];

export const APP_NAME = "Ma Ludothèque Stream";
export const STREAMER_NAME = "Le Streamer";